### ISSUE TITLE
As a Developer, I want to be able to test changes using Basic Page and Paragraphs

### ISSUE THREAD

**Issue by kreynen** [cu-uis/cu-starterkit-project#3]
There are several major changes happening with Drupal in the next year.

- Drupal 9.2.x is EoL in June 2022
- New Drupal 9.3 site use CKEditor 5 as default (but CKEditor 4 is still an option)
- Aten is only investing in the 2.x branch of https://www.drupal.org/project/layout_paragraphs (which requires CKEditor 5)
- [Drupal 10 will require PHP8.1](https://www.drupal.org/about/core/blog/drupal-10-will-require-php-81)
- CEditor 4 will no longer be included in Drupal 9.4/10. [It is already LTS and will be EoL in 2023](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_support.html#long-term-support-lts). 

Using a structure similar to https://github.com/cu-uis/cu-starterkit-project/tree/master/web/modules/custom/cusys_stylguide, we need to add some of the non-ODE specific Paragraphs to a Paragraph Layout field on the Basic Page content type to be able to start writing/running tests related to the Editor Experience.

**Comment by meschenbaum** [comment]
@kreynen - this has been added to master. I seemed to had forgotten to branch my changes so they went directly into master, my bad. I did pull all your changes down before though. So nothing should be broken or missing.

Please feel free to test/review.

**Comment by kreynen** [comment]
No worries. I've committed directly to master WAY more than I should have on this project. I just changed the rules for the master brach so the project admins can't commit directly to master unless we uncheck that.

<img width="758" alt="Screen Shot 2022-03-03 at 2 11 56 PM" src="https://user-images.githubusercontent.com/385234/156653855-84a0f1b1-8b33-41de-ba2e-8e57a6164938.png">

**Comment by meschenbaum** [comment]
Steps for testing basic Layout Paragraphs functionality on basic page content type:

1. As an CE, go to admin/content
2. Click Add Content
3. Select Basic Page
4. Add a Title
5. In the Content field, click the + to add a layout: Layout: CU Systems
6. Click the + inside the layout box and select Content: WYSIWYG
7. Type in some text and bold them
8. Save/publish the page and view
  - Expected Result: Page saved successfully
9. As an anonymous user, attempt to access page
  - The expected result is entered text on page

**Comment by meschenbaum** [comment]
There are issues around the new LP v2 settings for modals. 

Currently the only setting that allows you to edit in the modal is using pixels for the modal as it doesn't auto resize and the height can't use auto or percentages. You can use a percentage for the width and pixels for the height but it won't be mobile friendly.

**Comment by kreynen** [comment]
So is this a compatibility issue with Bootstrap/Barrio or an issue with layout_paragraphs 2.0.0-beta8 and ay theme? I'm not clear if this is the same issue as https://www.drupal.org/project/layout_paragraphs/issues/3252978 because the steps to reproduce the issue aren't included.
