### ISSUE TITLE
Bug - Change to root, project level composer.json has resulted in build failures

### ISSUE THREAD

**Issue by kreynen** [cu-uis/cu-starterkit-project#58]
**Describe the bug**

While the [build process is passing in GitHub](https://github.com/cu-uis/cu-starterkit-project/actions/workflows/php.yml), Autopilot is failing to merge the changes. The VRT tests aren't even running. This is most likely because of https://github.com/cu-uis/cu-starterkit-project/pull/56/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R29

Each project needs to that the upstream merge conflicts resolved in the master branch of the Pantheon repo before Autopilot will be able to run again.

<img width="1187" alt="Screen Shot 2022-05-20 at 8 18 34 AM" src="https://user-images.githubusercontent.com/385234/169548744-d62cd90e-3487-41ef-8296-da8a189e1e66.png">

**Comment by kreynen** [comment]
@meschenbaum  I'm not sure what you tried that wasn't working since you share your work. This is what I did to resolve the issue on https://dev-cu-starter-kit.pantheonsite.io/. The only difference between that site and the other is that it doesn't have a GitLab project.

The first step in trying to resolve this is to try to apply the Upstream updates using the Pantheon Dashboard's auto-resolve update. [Pantheon has documentation for resolving merge conflicts](https://pantheon.io/docs/git-resolve-merge-conflicts), but it is not Composer specific. 

<img width="998" alt="Screen Shot 2022-05-23 at 6 41 28 AM" src="https://user-images.githubusercontent.com/385234/169842630-7798d222-4056-4a3f-9eeb-fcc2af2afdf1.png">

<img width="1003" alt="Screen Shot 2022-05-23 at 6 42 37 AM" src="https://user-images.githubusercontent.com/385234/169842671-e29d3739-bcc4-4c64-b08f-59b750b88181.png">

If Pantheon cannot auto-resolve the conflict, you have to manually resolve this. The process for resolve this is really different from any other merge conflict beyond that it is happening the the composer.json. So unlike a conflict in a CSS that if resolved into invalid CSS that would negatively impact the rending of pages, not resolving a conflict in the composer.json will cause the build to fail or resources a project expects not to be included... causing the app to fail. 



1. Create a clean clone of the Pantheon dev instance using `git clone ssh://codeserver.dev.eb61423e-86f2-4155-8820-5a2774dc6011@codeserver.dev.eb61423e-86f2-4155-8820-5a2774dc6011.drush.in:2222/~/repository.git -b master cu-starter-kit`
2. Add the remote for https://github.com/cu-uis/cu-starterkit-project/ `git remote add github https://github.com/cu-uis/cu-starterkit-project/`
3. This step isn't necessary if you just added the remote repo, but in the future you need to be sure your local is aware of the changes to the remote `git fetch github master`
4. merge the remote changes into the Panhteon master branch (what the dev instance is linked to) using `git merge github/master`
5. resolve any merge conflicts
6. run `composer install` to update the composer.lock
7. commit those changes
8. push the update to Pantheon

At this point the hashes from GitHub are in the master branch on Pantheon. The Pantheon dashboard may still show that there are pending updates. Using the `Check Now` option will resolve that.

This process will work for the projects using GitLab because they will mirror the changes to the Pantheon master back into GitLab. As long as you pull before branching, you will have the updated composer.json changes in new branches.

If you branch before pulling, you will likely have a merge conflict when trying to deploy... but because we have a -force on the pipeline push, GitLab will just revert the changes made to resolve the merge conflicts with the upstream.

<img width="715" alt="Screen Shot 2022-05-23 at 7 32 59 AM" src="https://user-images.githubusercontent.com/385234/169844459-dd8aac24-a4a4-4797-905a-90437e9f754d.png">

**Comment by meschenbaum** [comment]
@kreynen thanks for this. I thought it was something like this with that Pantheon site and tried that, but ran into the issue you stated about branching before merging.

**Comment by meschenbaum** [comment]
@kreynen I manually update the online site and our starter kit site, but think there is something happening with Autopilot that is preventing updates being applied to the lock file. I can't see their log so am unable to really do any debugging.

After one manual update Autopilot discovered 4 new updates, which also included the manual update I just submitted. It then failed again to apply updates with no real useful message. I therefore did another manual update to capture those but feel there is still an issue in pantheon trying to apply updates.
