### ISSUE TITLE
As a CE, I want to be able to use LinkIt to add links with the WYSIWYG editor

### ISSUE THREAD

**Issue by kreynen** [cu-uis/cu-starterkit-project#7]
**Is your feature request related to a problem? Please describe.**

Linkit provides an easy interface for internal and external linking with wysiwyg editors by using an autocomplete field. It is used on online.cu.edu in 9.2.x. We need this to work in Drupal 9.2.x, 9.3.x, and 9.4.x/10 with CKEditor 4 and 5.

https://www.drupal.org/project/linkit/issues/3232190#comment-14425790 documents the compatibility issues with CKEditor 5 (required in Drupal 10).

**Describe the solution you'd like**

We need something that sets up the current CKEditor configurations and the steps to upgrade until it fails to work. 

**Discovery**

Not sure if a dedicated cusys_ckeditor or cusys_wysiwyg module makes sense. Maybe this is the type of feature we should role into a "super" module?

**Comment by meschenbaum** [comment]
**BUILD VERSIONS:**
- Drupal: 9.3.8
- PHP: 8.0.13
- MariaDB: 19.4.22
- LinkIt: 6.0.0-beta3

Steps for testing basic LinkIt functionality on basic page content type within CKEditor:

1. Install CU Content Bundle. 
2. As a CE, go to admin/content
4. Click Add Content
5. Select Basic Page
6. Add a Title
7. In the Content field, click the + to add a layout: Layout: CU Systems
8. Click the + inside the layout box and select Content: WYSIWYG
9. Type in some text
10. Save/publish the page and view
    a. Expected Result: Page saved successfully
11. As an anonymous user, attempt to access page
    a. The expected result is entered text on page
12. Repeat steps 2-11 for two more pages but make one of them unpublished.
13. Go to edit one of the three pages you created.
14. Within the Content WYSIWYG field, use the toolbar link button to add a link, to a selected word(s), to one of the other pages.
    a. Expected Result: You should see the Published/UnPublished pages show up in auto-complete dropdown.
    b. When a page is selected and the link is saved, it should have created a link to the page.
15. Now create another link to a URL, select the url in the auto-complete list
    a. Expected Result: You should have created an external link
16. Save your changes
    a. Expected Result: The page can be visited as any type of user and links work as expected.
    b. Expected Anonymous User Result: They should be able to access all pages and use the links as normal but get an "Access Denied" to any unpublished page.

![Screen Shot 2022-03-18 at 3 51 13 PM](https://user-images.githubusercontent.com/6807288/159088968-af69d7e9-42a3-4e61-831a-8cfa83acb991.png)

![Screen Shot 2022-03-18 at 3 52 32 PM](https://user-images.githubusercontent.com/6807288/159089088-fad00e95-4209-43af-bd9a-1ad0f784705b.png)

![Screen Shot 2022-03-18 at 3 52 46 PM](https://user-images.githubusercontent.com/6807288/159089270-90032fbc-213e-4da0-afd2-c13f483257cc.png)

![Screen Shot 2022-03-18 at 3 53 04 PM](https://user-images.githubusercontent.com/6807288/159089333-73fba0dd-5b34-4eed-bed2-03b89c227011.png)

![Screen Shot 2022-03-18 at 3 53 22 PM](https://user-images.githubusercontent.com/6807288/159089419-8f2de4b0-e5c3-427e-a48e-27943206f471.png)

![Screen Shot 2022-03-18 at 3 53 46 PM](https://user-images.githubusercontent.com/6807288/159089503-ad62ee08-c72f-454e-aad4-36d7d233a899.png)

![Screen Shot 2022-03-18 at 3 53 58 PM](https://user-images.githubusercontent.com/6807288/159089586-aae707f7-63f1-4df2-b0f2-5179e71a873c.png)

![Screen Shot 2022-03-18 at 3 54 10 PM](https://user-images.githubusercontent.com/6807288/159089651-0f4e51f6-3101-4494-86c1-8ad988563c6a.png)

**Discovered Issues:**

- Current version of LinkIt has bug with using enter key to select link in editor window. When you hit enter it removes the modal and takes you an add link page. From the page you cannot add the link. This could be an issue with the basic themes we're using or an issue within LinkIt.
- LinkIt has a lot of open issues and no stable version for 9.0: https://www.drupal.org/project/issues/linkit?status=All&categories=All

![Screen Shot 2022-03-18 at 3 58 41 PM](https://user-images.githubusercontent.com/6807288/159091565-a95016f2-d3d1-4cbe-b326-2c7bf6930dc4.png)

**Comment by meschenbaum** [comment]
**Note:**

As we expand the testing, we should add other modules that will interact with LinkIt:

- Url Alias
- Link Attributes
- Editor allowed tags/attributes
