### ISSUE TITLE
Evaluate - Allow 9.4.0 upgrade 

### ISSUE THREAD

**Issue by kreynen** [cu-uis/cu-starterkit-project#80]
**Describe the options**

The alternative is to or pin the CU Online project to 9.3.x in GitLab. Auto Pilot has already updated https://online-dev.cu.edu/ to 9.4.0. To stay on 9.4.0, we need to test the changes in https://www.drupal.org/project/drupal/releases/9.4.0.

**Comment by kreynen** [comment]
The only issue I found testing 9.4.0 was that Drupal now recommends upgrading to PHP version 8.1 or higher for the best ongoing support in /admin/reports/status. This is managed in https://github.com/cu-uis/cu-starterkit-project/blob/master/pantheon.upstream.yml#L5 for new installs and a project specific file like https://gitlab.cu.edu/uis-webdev/online-cu-starterkit/-/blob/master/pantheon.yml#L4 that is created as part of the install process.

**Comment by meschenbaum** [comment]
It looks like LinkIt, within CKEditor, is using node instead of aliases.

**Comment by kreynen** [comment]
The 3rd place this would need to change is in .ddev/config.yml

```
name: cu-starterkit-project
type: drupal9
docroot: web
php_version: "8.1"
```
