### ISSUE TITLE
Bug - Theme updates not properly installed on existing sites

### ISSUE THREAD

**Issue by meschenbaum** [cu-uis/cu-starterkit-project#85]
**Describe the bug**
When the CU Base theme issues a new tag and the starter kit composer is updated to include the new tag, composer does not overwrite the files if the theme already exists. This has been reported by Matt E. and Tim Stalker.

**To Reproduce**
1. Go to an existing Starterkit site, that is using an older cu_base version, or create a new site with an older cu_base version.
2. Update the composer.json to a newer cu_base version
3. Run `composer install`
4. You'll see that composer shows the install of the newer version, but if you check the directory it will not have the newer code.

**Expected behavior**
When the composer is updated to use a newer version, I expect it to overwrite the files in the theme directory with the newer code.

This was happening on local environments and Tim noted this on his test sites.

**Comment by meschenbaum** [comment]
@kreynen Tim verified this in our call that he was having the same issue of the theme not updating. Deleting the theme folder and re-running `composer install` did install the correct theme version.

We're not sure what is causing this or what the solution may be. It may be resolved if moved it to packagist or something.

**Comment by kreynen** [comment]
The problem is that the .git dir is being included in the build and thus not picked up when the project is updated.

<img width="564" alt="Screen Shot 2022-07-21 at 7 26 35 AM" src="https://user-images.githubusercontent.com/385234/180229786-8e1c00f0-dc8d-46d2-a36c-fe2118c527db.png">

Not sure why that happens for cu_base and not https://github.com/cu-uis/cu-starterkit-project/blob/master/composer.json#L17, but this is the reason why the cu_base dir needs to be manually deleted

**Comment by kreynen** [comment]
https://stackoverflow.com/questions/25981292/how-to-make-composer-not-create-a-git-directory-for-a-package suggests a few different ways to fix this.

**Comment by meschenbaum** [comment]
Fixed by changing reference in composer.json

**Comment by meschenbaum** [comment]
@kreynen @johnquest can you two check if this change will update the CU Base theme to the latest 1.0.3 tag?

**Comment by kreynen** [comment]
I responded in Teams, but updating the version in the info.yml will surface the version in the Drupal UI AND with any any dependencies. I opened https://github.com/cu-uis/cu_base/pull/13. Even when this is managed by Packagist, the version needs to be maintained in both places.

This is one of many things Drupal.org does for projects.

**Comment by johnquest** [comment]
I successfully updated the code via the pantheon dashboard with the branch set to "expose-version-in-ui" in the cu_base repo.
